### ISSUE TITLE
Add list of projects

### ISSUE THREAD

**Issue by wdoug** [codefordenver/code-for-denver-site#1]

**Comment by dviramontes** [comment]
got some really good feed back from Stacie and Joseph on this.
will work on implementing this, this week

**Comment by dviramontes** [comment]
subtask: update get involved section

**Comment by dviramontes** [comment]
assigning @wdoug since he got something started  for this

**Comment by wdoug** [comment]
Closing this, since, while we need to update our project list, we at least have an outdated one. (Updating can be a separate task)
