### ISSUE TITLE
Dynamic Meetup Calendar Component

### ISSUE THREAD

**Issue by jenshurley** [codefordenver/code-for-denver-site#116]

**Comment by Dsenza** [comment]
Making this component is pretty simple, outside of getting the data for what our next meetup is.  Tried messing with the meetup API, I gave up.  Any ideas on how to provide this info to the component?

**Comment by jenshurley** [comment]
Is this a matter of needing to know API key?  I wonder how Willy got the
meetup info on the existing site.

**Comment by Dsenza** [comment]
They use something called CORS coupled with OAuth to be able to access their API from a different domain, and I couldn't figure out how to get that all setup.

**Comment by jenshurley** [comment]
for now we have a workaround #155, but eventually it would be nice to pull this data in from Meetup
