### ISSUE TITLE
Header Image Changes With Tabbing

### ISSUE THREAD

**Issue by dkoloditch** [codefordenver/code-for-denver-site#130]
Image at the top of the page transitions to another image with each tab click. Visually appealing and serves as an additional navigation reference.

Branch: redesign

**Comment by jenshurley** [comment]
- What We Do - cfd-1.jpg
- Want to Help - cfd-10.jpg
- Can We Help You - cfd-6.jpg
- Blog/Voice - cfd-9.jpg
-Want to Learn - cfd-8.jpg
