### ISSUE TITLE
Add slogan / mission statement

### ISSUE THREAD

**Issue by wdoug** [codefordenver/code-for-denver-site#23]

**Comment by dkoloditch** [comment]
Do the About section and sub-header ("Make Denver Awesome") cover this? If not, does Code for America provide a set of guidelines at all? Apologies for my ignorance here.

**Comment by dviramontes** [comment]
Thanks for bringing this up. Yeah it needs to be updated. 
Maybe something like 
"STRENGTHENING OUR LOCAL COMMUNITY"

**Comment by wdoug** [comment]
I think we will want to revisit this, but in the mean time `Strengthening Our Local Community` is much better than what we have currently. Do you want to create a PR for that @dviramontes?

**Comment by dviramontes** [comment]
sure
