### ISSUE TITLE
Add onboarding / getting started resources

### ISSUE THREAD

**Issue by wdoug** [codefordenver/code-for-denver-site#26]
Content reference:

https://github.com/codefordenver/org

**Comment by dkoloditch** [comment]
@wdoug @dviramontes: is the plan to keep Getting Started and Get Involved as separate entities? 

If so, will the Getting Started info live on a static page somewhere, like Github?

Otherwise, should I go ahead and start moving the Q & A's from the document to the Get Involved section in the david/get-involved branch?

**Comment by wdoug** [comment]
Based off the meeting on Monday, it sounded we want to have them separate at least for now. 

I was thinking it could be good to add it to the org repo as a markdown file, then we can just link to it from multiple locations. I guess the main thing is just make it accessible (could even link to the Google doc) , and we can iterate over time. What do you think?

**Comment by dviramontes** [comment]
+1

**Comment by hasuf** [comment]
+1 on keeping Onboarding and Getting Involved separate but having Onboarding accessible through a link (eg, perhaps from a "How do I get started with tools/code"?)

**Comment by dviramontes** [comment]
yeah im working on that a bit more tonight, i have an idea but i welcome any others.

**Comment by dkoloditch** [comment]
Onboarding / Getting Started added to org README. Thanks @dviramontes!

**Comment by dviramontes** [comment]
I just realized I should have been more specific, @hasuf i'll be working on consolidating all the docs in a single page. We talked briefly about this last time, basically, links to important docs either on google drive or GitHub markdown files like the one @dkoloditch wrote for us. Part of our effort to make everything more transparent.

I got the markdown files to render as html, just need to learn a bit more about the google drive api.

**Comment by wdoug** [comment]
:+1: @dviramontes

**Comment by wdoug** [comment]
@dkoloditch, what should we do with this card? Is it linked to on the site currently?

**Comment by wdoug** [comment]
Blocked while we redesign the site
