### ISSUE TITLE
Figure out what learning resources we should include

### ISSUE THREAD

**Issue by wdoug** [codefordenver/code-for-denver-site#3]

**Comment by wdoug** [comment]
Ideas:

- Data resources
- Resources for learning (Code, etc)
- How to get started with the brigade (e.g. flowdock tutorial)

**Comment by dkoloditch** [comment]
Here's a list of general and RoR related resources I've been compiling: http://owowthathurts.blogspot.com/2013/10/ruby-and-rails-learning-resources.html

Are we recommending specific languages/frameworks?

**Comment by AnnetteAlexis018** [comment]
Hey, we're working on the Open Data Census in Miami. Thought you Might want to include! http://us-city.census.okfn.org/place/denver

**Comment by wdoug** [comment]
Thanks @AnnetteAlexis018!
