### ISSUE TITLE
Add /org section to the site

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/code-for-denver-site#38]
add an onboarding page
basically a page about our processes
what tools we use and how to get access to flowdock, github, waffle, etc
addresses #22

**Comment by wdoug** [comment]
@dviramontes what is the status of this issue (opened a year ago). Should I close it, or move it back to the backlog?

**Comment by wdoug** [comment]
I am going to close this as I think it is already covered between our members page, and #26
