### ISSUE TITLE
Put video on website

### ISSUE THREAD

**Issue by switzersc** [codefordenver/code-for-denver-site#54]
Get codeacross video, make sure it's hosted publicly on vimeo, and put on main page of website

**Comment by Lucidpaper** [comment]
for reference vimeo.com/126984194

**Comment by reonespot** [comment]
It would be awesome if there were a button to watch the video right on the home banner that when clicked, payed the video at the width of the page.  It's doable with vimeo. Thoughts on this?

**Comment by reonespot** [comment]
It would be awesome if there were a button to watch the video right on the home banner that when clicked, payed the video at the width of the page. It's doable with vimeo. Thoughts on this?

**Comment by switzersc** [comment]
It would be awesome if there were a button to watch the video right on the home banner that when clicked, payed the video at the width of the page. It's doable with vimeo. Thoughts on this?
