### ISSUE TITLE
Redesign website structure and navigation

### ISSUE THREAD

**Issue by wdoug** [codefordenver/code-for-denver-site#64]
As a CfD member, I want to be able to find info I am looking for, and have a clear call to action.
__and__
As a prospective member, I want information on the brigade, and clear action steps to get involved.

**Comment by nickpalmer789** [comment]
Here are the groups of important things that we came up with tonight using the notecard method. The following are in no particular order:
-Get involved (Call to action)
-Donate/Invest in CFD
-Different skillsets that are welcome
-About us/Mission statement
-Become a partner/funder (Form?)
-Project portfolio

Items that we considered adding to the meetup page specifically:
-Easy Onboarding Section (Maybe a repo with guides about how to get onboarded)
-Encouragement to come to a meetup

**Comment by wdoug** [comment]
I really don't want to have analysis paralysis (let's act in the spirit of GEFN - Good Enough for now), but it might be interesting to peruse some of the other brigades' websites. A list can be obtained from the cfapi, or directly from this json document: https://github.com/codeforamerica/brigade-information/blob/master/organizations.json

**Comment by wdoug** [comment]
Or maybe even better, just perusing on http://www.codeforamerica.org/brigade/

**Comment by jenshurley** [comment]
Maybe this is about my Kanban ignorance - can I move this to done?  I consider the wireframe that Ryan did to be the GEFN version of the card sort we did.

**Comment by wdoug** [comment]
Sure that sounds good.
[Ryan's mockup](https://drive.google.com/file/d/0B7y9DM_K_7vFVFVyXzVhSDZzMTQ/view)

**Comment by wdoug** [comment]
Let's make the list that Nick Posted above into their own waffle cards. Then close this card?
