### ISSUE TITLE
Refactor separate pages to use react

### ISSUE THREAD

**Issue by wdoug** [codefordenver/code-for-denver-site#70]
/CodeAcross/
/members/

**Comment by jenshurley** [comment]
transfer over what Zack has done for the static part

**Comment by dkoloditch** [comment]
@wdoug @jenshurley. I'm a little confused on this one. What are the details/requirements?

**Comment by wdoug** [comment]
Right now these pages are just raw html & js. I suppose it isn't critical to update them. Maybe we should just close this unless it is actually needed for something.
