### ISSUE TITLE
Update projects carousel

### ISSUE THREAD

**Issue by wdoug** [codefordenver/code-for-denver-site#77]
As a user, I'd like up to date info on projects.

**Comment by jenshurley** [comment]
As a potential funder, partner or volunteer, I would like to learn about past projects so I can understand the kinds of things Code for Denver does.

**Comment by jenshurley** [comment]
#57

**Comment by whitebird08** [comment]
merged new carousel into redesign branch

**Comment by wdoug** [comment]
I'm marking this as closed as a duplicate of #57
