### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by jenshurley** [codefordenver/code-for-denver-site#95]
rough up static page as laid out in Dave’s mockups

**Comment by jenshurley** [comment]
@zacharyrose should we move this to done since you refactored it into react?

**Comment by zacharyrose** [comment]
@jenshurley I Was going to ask you about this, wasn't sure if this was a major task or not, due to the title being a little vague.  Maybe we should consider this the initial static HTML design for clarity and just close it out.
