### ISSUE TITLE
Convert static to React on branch redesign and set up structure

### ISSUE THREAD

**Issue by jenshurley** [codefordenver/code-for-denver-site#99]

**Comment by dkoloditch** [comment]
Is this different from #70?

**Comment by jenshurley** [comment]
@dkoloditch, this card is about taking [Zack's work on the static HMTL and CSS](http://zacharyrose.net/codefordenver-redesign/) and moving it into React  -- the separate divs become components I think. 

@wdoug said that it was different than #70.

**Comment by dkoloditch** [comment]
Ah, OK thanks Jen. I'm happy to help.

@zacharyrose, what's the plan / timetable as far as getting this code into the redesign branch so we can start the transition? I'm guessing we're just going to start with a clean slate. Looking at the current redesign branch, there's a lot of old code in there.

**Comment by zacharyrose** [comment]
@dkoloditch, made some progress tonight.  Separated elements into separate React components and generated header dynamically using the process that was in place earlier.  You can see my changes on the branch "redesign-importcontent"
